const getAutoGeneratePassword = () => {
  const maxLength = 32
  const minLength = 8

  // Cognitoで使用可能な文字を用意
  const lowerCase = 'abcdefghijklmnopqrstuvwxyz'
  const upperCase = lowerCase.toLocaleUpperCase()
  const numbers = '0123456789'
  const symbols = '%&$#()' // TODO 直す
  const chars = lowerCase + upperCase + numbers + symbols

  // Cognitoのパスワードルールを正規表現で設定
  const lowerCaseRegex = new RegExp('[a-z]')
  const numberRegex = new RegExp('[0-9]')

  // autoGeneratedPasswordが以上の条件を満たせばvalidがtrueになる
  let valid = false
  let autoGeneratedPassword: string

  while (!valid) {
    autoGeneratedPassword = ''
    // パスワードの文字数を上で決めた範囲内でランダムに決定
    const randomLength =
      Math.floor(Math.random() * (maxLength - minLength)) + minLength
    while (autoGeneratedPassword.length < randomLength) {
      const index = Math.floor(Math.random() * chars.length)
      autoGeneratedPassword += chars[index]
    }

    // パスワードが上で決定した条件をすべて満たしているかチェック
    // TODO 記号とか追加
    valid =
      minLength <= autoGeneratedPassword.length &&
      autoGeneratedPassword.length <= maxLength &&
      lowerCaseRegex.test(autoGeneratedPassword) &&
      numberRegex.test(autoGeneratedPassword)
  }
  return autoGeneratedPassword
}

