export const getAutoGeneratePassword = (): string => {
  const maxLength = 32;
  const minLength = 8;

  // Cognitoで使用可能な文字を用意
  const lowerCase = 'abcdefghijklmnopqrstuvwxyz';
  const upperCase = lowerCase.toUpperCase(); // toLocaleUpperCaseからtoUpperCaseに変更
  const numbers = '0123456789';
  // 要件に合わせて特殊文字のリストを更新
  const symbols = '^$*.[]{}()?-"!@#%&/\\,><\':;|_~`+='; 
  const chars = lowerCase + upperCase + numbers + symbols;

  // Cognitoのパスワードルールを正規表現で設定
  const lowerCaseRegex = new RegExp('[a-z]');
  const upperCaseRegex = new RegExp('[A-Z]');
  const numberRegex = new RegExp('[0-9]');
  const symbolRegex = new RegExp('[\\^\\$\\*\\.\\[\\]\\{\\}\\(\\)\\?\\-\\"\\!\\@\\#\\%\\&\\/\\\\,\\>\\<\\\'\\:\\;\\|_\\~\\`\\+\\=]');

  let autoGeneratedPassword = '';
  do {
    autoGeneratedPassword = '';
    const randomLength = Math.floor(Math.random() * (maxLength - minLength + 1)) + minLength;
    while (autoGeneratedPassword.length < randomLength) {
      const index = Math.floor(Math.random() * chars.length);
      autoGeneratedPassword += chars[index];
    }
  } while (
    !lowerCaseRegex.test(autoGeneratedPassword)
    || !upperCaseRegex.test(autoGeneratedPassword)
    || !numberRegex.test(autoGeneratedPassword)
    || !symbolRegex.test(autoGeneratedPassword)
  );

  return autoGeneratedPassword;
}
