AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3BucketForWebsite:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        #ErrorDocument: error.html

  S3BucketPolicyForWebsite:
    Type: 'AWS::S3::BucketPolicy'
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref S3BucketForWebsite
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAC}'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3BucketForWebsite}/*'

  CloudFrontOAC:
    Type: 'AWS::CloudFront::OriginAccessControl'
    DeletionPolicy: Retain
    Properties:
      OriginAccessControlConfig:
        Description: 'OAC for accessing chococalc S3 bucket'
        Name: 'chococalc-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistributionForWebsite:
    Type: 'AWS::CloudFront::Distribution'
    DeletionPolicy: Retain
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt S3BucketForWebsite.DomainName
            Id: S3Origin
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: allow-all
